baseURL = "https://soilnordiccircle.org"
languageCode = "en-us"
title = "The Southern Illinois Nordic Circle"
theme = "hugo-theme-stack"

[params]
mainSections = ["posts"]
showPoweredBy = false
showToc = false

[params.sidebar]
avatar = ""
title = "The Southern Illinois Nordic Circle"
description = "Exploring and preserving Nordic heritage in Southern Illinois"

[params.widgets]
homepage = [
  { type = "search" },
  { type = "archives", params = { limit = 5 } },
  { type = "tag-cloud", params = { limit = 10 } },
]
page = [{ type = "toc" }, { type = "related" }]
