baseURL = "https://soilnordiccircle.org"

theme = "soilnordiccircle"

title = "The Southern Illinois Nordic Circle"

languageCode = "en-us"
languageName = "English"

[markup.goldmark.renderer]
unsafe = true
